# Generated by Django 2.2.1 on 2019-06-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCompleto', models.CharField(help_text='Ingrese Su nombre Completo', max_length=40)),
                ('sexo', models.CharField(help_text='ingrese su Sexo Ejemplo M = Masculino, F = Femenino', max_length=1)),
                ('curso', models.CharField(help_text='801 - 802 - 803 - 804', max_length=10)),
                ('estrato', models.IntegerField(help_text='1 - 2 - 3 - 4')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
