# Generated by Django 2.2.1 on 2019-06-13 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isomaticAppWeb', '0002_estudiante_registrado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='registrado',
        ),
    ]
