# Generated by Django 2.2.1 on 2019-06-17 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isomaticAppWeb', '0007_pregunta2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta9',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(max_length=255)),
                ('fecha_registro_P09', models.DateTimeField(auto_now_add=True)),
                ('preguntaGuardada', models.BooleanField(default=False)),
                ('identificadorEstudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pregunta9', to='isomaticAppWeb.Estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(max_length=255)),
                ('fecha_registro_P08', models.DateTimeField(auto_now_add=True)),
                ('preguntaGuardada', models.BooleanField(default=False)),
                ('identificadorEstudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pregunta8', to='isomaticAppWeb.Estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(max_length=255)),
                ('fecha_registro_P07', models.DateTimeField(auto_now_add=True)),
                ('preguntaGuardada', models.BooleanField(default=False)),
                ('identificadorEstudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pregunta7', to='isomaticAppWeb.Estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(max_length=255)),
                ('fecha_registro_P05', models.DateTimeField(auto_now_add=True)),
                ('preguntaGuardada', models.BooleanField(default=False)),
                ('identificadorEstudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pregunta5', to='isomaticAppWeb.Estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(max_length=255)),
                ('fecha_registro_P04', models.DateTimeField(auto_now_add=True)),
                ('preguntaGuardada', models.BooleanField(default=False)),
                ('identificadorEstudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pregunta4', to='isomaticAppWeb.Estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(max_length=255)),
                ('fecha_registro_P03', models.DateTimeField(auto_now_add=True)),
                ('preguntaGuardada', models.BooleanField(default=False)),
                ('identificadorEstudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pregunta3', to='isomaticAppWeb.Estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(max_length=255)),
                ('fecha_registro_P010', models.DateTimeField(auto_now_add=True)),
                ('preguntaGuardada', models.BooleanField(default=False)),
                ('identificadorEstudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pregunta10', to='isomaticAppWeb.Estudiante')),
            ],
        ),
    ]
