# Generated by Django 2.2.1 on 2019-06-17 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isomaticAppWeb', '0008_pregunta10_pregunta3_pregunta4_pregunta5_pregunta7_pregunta8_pregunta9'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(max_length=255)),
                ('fecha_registro_P06', models.DateTimeField(auto_now_add=True)),
                ('preguntaGuardada', models.BooleanField(default=False)),
                ('identificadorEstudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pregunta6', to='isomaticAppWeb.Estudiante')),
            ],
        ),
    ]
