# Generated by Django 2.2.1 on 2019-07-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isomaticAppWeb', '0011_remove_estudiante_numerodocumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta1',
            name='respuestaCorrectaUno',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pregunta10',
            name='respuestaCorrectaDiez',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pregunta2',
            name='respuestaCorrectaDos',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pregunta3',
            name='respuestaCorrectaTres',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pregunta4',
            name='respuestaCorrectaCuatro',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pregunta5',
            name='respuestaCorrectaCinco',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pregunta6',
            name='respuestaCorrectaSeis',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pregunta7',
            name='respuestaCorrectaSiete',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pregunta8',
            name='respuestaCorrectaOcho',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pregunta9',
            name='respuestaCorrectaNueve',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
