# Generated by Django 2.2.1 on 2019-07-15 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isomaticAppWeb', '0012_auto_20190701_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntajeTotalEstudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntajeTotal', models.CharField(max_length=255)),
                ('fecha_registro_guardado', models.DateTimeField(auto_now_add=True)),
                ('identificadorEstudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PuntajeTotalEstudiante', to='isomaticAppWeb.Estudiante')),
            ],
        ),
    ]
