# Generated by Django 2.2.1 on 2019-07-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isomaticAppWeb', '0014_puntajetotalestudiante_plataforma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuestaPregunta1', models.PositiveSmallIntegerField(choices=[(1, 'MINIMO'), (2, 'POCO'), (3, 'BASTANTE')], verbose_name='1. ¿Qué tanto sabe para resolver este problema?')),
                ('respuestaPregunta2', models.PositiveSmallIntegerField(choices=[(1, 'MINIMO'), (2, 'POCO'), (3, 'BASTANTE')], verbose_name='2. ¿Conoce estrategias para resolver este problema?"')),
                ('respuestaPregunta3', models.PositiveSmallIntegerField(choices=[(1, 'MINIMO'), (2, 'POCO'), (3, 'BASTANTE')], verbose_name='3. ¿Qué tanto sirve el plan que tiene para resolver este problema? ')),
                ('respuestaPregunta4', models.PositiveSmallIntegerField(choices=[(1, 'MINIMO'), (2, 'POCO'), (3, 'BASTANTE')], verbose_name='4. ¿Qué conocimientos tiene sobre los temas relacionados con la solución de problemas? ')),
                ('respuestaPregunta5', models.PositiveSmallIntegerField(choices=[(1, 'MINIMO'), (5, 'BAJA'), (6, 'ALTA'), (7, 'SUPERIOR')], verbose_name='5. El valor de la meta que se ha propuesto es:')),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
