# Generated by Django 2.2.1 on 2019-07-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isomaticAppWeb', '0015_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Final',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuestaPregunta11', models.PositiveSmallIntegerField(choices=[(1, 'MINIMO'), (2, 'POCO'), (3, 'BASTANTE'), (8, 'MUCHO')], verbose_name='11. ¿Qué nivel de conocimiento ha alcanzado  con la soluciones que ha realizado hasta el momento?')),
                ('respuestaPregunta12', models.PositiveSmallIntegerField(choices=[(1, 'MINIMO'), (2, 'POCO'), (3, 'BASTANTE'), (4, 'TOTALMENTE')], verbose_name='12. ¿Qué  tanto uso las ayudas para resolver  los problemas?')),
                ('respuestaPregunta13', models.PositiveSmallIntegerField(choices=[(1, 'MINIMO'), (2, 'POCO'), (3, 'BASTANTE'), (4, 'TOTALMENTE')], verbose_name='13. ¿Qué tanto he aprendido en la solución de problemas?')),
                ('respuestaPregunta14', models.PositiveSmallIntegerField(choices=[(1, 'MINIMO'), (2, 'POCO'), (3, 'BASTANTE'), (4, 'TOTALMENTE')], verbose_name='14. ¿En que nivel alcance la meta propuesta al iniciar con la solución de problemas?')),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModuloDuranteCinco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuestaPregunta', models.PositiveSmallIntegerField(choices=[(1, 'MINIMO'), (2, 'POCO'), (3, 'BASTANTE'), (4, 'TOTALMENTE')], verbose_name='10. ¿En qué nivel considero que estoy logrando la solución del problema?')),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModuloDuranteCuatro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuestaPregunta', models.PositiveSmallIntegerField(choices=[(1, 'MINIMO'), (2, 'POCO'), (3, 'BASTANTE'), (4, 'TOTALMENTE')], verbose_name='9.¿Que tanto replanteo sus estrategias y uso unas  nuevas?')),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModuloDuranteDos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuestaPregunta', models.PositiveSmallIntegerField(choices=[(1, 'MINIMO'), (2, 'POCO'), (3, 'BASTANTE'), (5, 'MUCHO')], verbose_name='7. El tiempo que puede durar solucionando el problema es:')),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModuloDuranteTres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuestaPregunta', models.PositiveSmallIntegerField(choices=[(1, 'MINIMO'), (2, 'POCO'), (3, 'BASTANTE'), (4, 'TOTALMENTE')], verbose_name='8. ¿Qué tanto uso las estrategias que planeo en la solución de problemas?')),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModuloDuranteUno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuestaPregunta', models.PositiveSmallIntegerField(choices=[(1, 'MINIMO'), (2, 'POCO'), (3, 'BASTANTE'), (4, 'TOTALMENTE')], verbose_name='6. ¿Si no comprende el problema tiene algún plan para encontrar la solución? Indique el nivel de precisión.')),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='respuestaPregunta1',
            field=models.PositiveSmallIntegerField(choices=[(1, 'MINIMO'), (2, 'POCO'), (3, 'BASTANTE'), (4, 'TOTALMENTE')], verbose_name='1. ¿Qué tanto sabe para resolver este problema?'),
        ),
        migrations.AlterField(
            model_name='book',
            name='respuestaPregunta2',
            field=models.PositiveSmallIntegerField(choices=[(1, 'MINIMO'), (2, 'POCO'), (3, 'BASTANTE'), (4, 'TOTALMENTE')], verbose_name='2. ¿Conoce estrategias para resolver este problema?"'),
        ),
        migrations.AlterField(
            model_name='book',
            name='respuestaPregunta3',
            field=models.PositiveSmallIntegerField(choices=[(1, 'MINIMO'), (2, 'POCO'), (3, 'BASTANTE'), (4, 'TOTALMENTE')], verbose_name='3. ¿Qué tanto sirve el plan que tiene para resolver este problema? '),
        ),
        migrations.AlterField(
            model_name='book',
            name='respuestaPregunta4',
            field=models.PositiveSmallIntegerField(choices=[(1, 'MINIMO'), (2, 'POCO'), (3, 'BASTANTE'), (4, 'TOTALMENTE')], verbose_name='4. ¿Qué conocimientos tiene sobre los temas relacionados con la solución de problemas? '),
        ),
    ]
