# Generated by Django 2.0 on 2019-07-21 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isomaticAppWeb', '0016_auto_20190715_0339'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='PrimerModulo',
        ),
    ]
