# Generated by Django 2.2.4 on 2019-09-02 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isomaticAppWeb', '0017_auto_20190721_0218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modulodurantecinco',
            old_name='respuestaPregunta',
            new_name='respuestaPregunta10',
        ),
        migrations.RenameField(
            model_name='modulodurantecuatro',
            old_name='respuestaPregunta',
            new_name='respuestaPregunta9',
        ),
        migrations.RenameField(
            model_name='modulodurantedos',
            old_name='respuestaPregunta',
            new_name='respuestaPregunta7',
        ),
        migrations.RenameField(
            model_name='modulodurantetres',
            old_name='respuestaPregunta',
            new_name='respuestaPregunta8',
        ),
        migrations.RenameField(
            model_name='moduloduranteuno',
            old_name='respuestaPregunta',
            new_name='respuestaPregunta6',
        ),
    ]
