"""
Django settings for isomatic project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

import django_heroku


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'g#k_-j_l=_-s)7c5_v^lk8h8vu!a@+sn_-!mce2vtj9mu=ad3#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = []


# TODO CONFIGURAR ENVIO DE EMAIL

# TODO CONFIGURAR ENVIO DE EMAIL

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    # 'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # para realizar debug
    # 'debug_toolbar',
    'isomaticAppWeb.apps.IsomaticappwebConfig',
    'crispy_forms',
    'widget_tweaks',

    # 'registration',DebugToolbarMiddleware
]
# ///TODO PARA LOCAL Y CON ESTA VERSION SE MANEJA DJANGO 2.2.1
MIDDLEWARE = [
   # 'debug_toolbar.middleware.DebugToolbarMiddleware',
   'django.middleware.security.SecurityMiddleware',
   'django.contrib.sessions.middleware.SessionMiddleware',
   'django.middleware.common.CommonMiddleware',
   'django.middleware.csrf.CsrfViewMiddleware',
   'django.contrib.auth.middleware.AuthenticationMiddleware',
   'django.contrib.messages.middleware.MessageMiddleware',
   'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

# ///TODO PARA PRUDCUCCION Y CON ESTA VERSION SE MANEJA DJANGO 1.9.3
# MIDDLEWARE_CLASSES = [
#      'django.middleware.security.SecurityMiddleware',
#      'django.contrib.sessions.middleware.SessionMiddleware',
#      'django.middleware.common.CommonMiddleware',
#      'django.middleware.csrf.CsrfViewMiddleware',
#      'django.contrib.auth.middleware.AuthenticationMiddleware',
#      'django.contrib.messages.middleware.MessageMiddleware',
#      'django.middleware.clickjacking.XFrameOptionsMiddleware',
#  ]

ROOT_URLCONF = 'isomatic.urls'

CRISPY_TEMPLATE_PACK = 'bootstrap4'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'isomatic.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

# todo en local se comenta esta linea::
# Todo esta base de datos las tenemos contra produccion
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'deio7c3ebdsluu',
#         'USER': 'yxhymsnjtwfpju',
#         'PASSWORD': '61970277004d896d61c605939b2147b9da69a80f36f460b08bd4b0c6f71c72d8',
#         'HOST': 'ec2-54-163-226-238.compute-1.amazonaws.com',
#         'PORT': '5432',
#     }
# }
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'd7duqftmb7n259',
#         'USER': 'qspxaeffqeozhx',
#         'PASSWORD': 'e59bf8b5daa56a85ef4f26f73931cae34bd962a9d8df43e767820953b4376580',
#         'HOST': 'ec2-50-16-197-244.compute-1.amazonaws.com',
#         'PORT': '5432',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'dcf1kn79fdseaa',
        'USER': 'zdvipxqgnvaqbx',
        'PASSWORD': '89b68e009afd008ce77e7212052c49d9368273e9bbed4889f2620e8def62724f',
        'HOST': 'ec2-107-22-211-248.compute-1.amazonaws.com',
        'PORT': '5432',
    }
}



# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': 'mydatabase',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

# STATIC_URL = '/static/'

# todo nuevas lineas
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'

# Extra places for collectstatic to find static files.
# TODO  esta linea busca los archivos estaicos  en local de descomenta y en produccion se comenta
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)
# ACCOUNT_ACTIVATION_DAYS = 7 # One-week activation window; you may, of course, use a different value.
# REGISTRATION_AUTO_LOGIN = True # Automatically log the user in.
django_heroku.settings(locals())

# INTERNAL_IPS = [
#     # ...
#     '127.0.0.1',
#     # ...
# ]
